main: serversystem.main.ServerSystem
name: ServerSystem
version: '3.1'
author: Der_Zauberer
api-version: 1.14
api: none

commands:
  admin:
    description: Open the admin menu
    usage: /<command>
    permission: serversystem.command.admin
  back:
    description: Teleport back to the last location
    usage: /<command>
    permission: serversystem.command.back
  build:
    description: Allow the player to build in protected worlds
    usage: /<command> [<player>]
    permission: serversystem.command.build
  enderchest:
    description: Open the enderchest of a player
    usage: /<command> [<player>]
    permission: serversystem.command.enderchest
  fly:
    description: Allow the player to fly
    usage: /<command> [<player>]
    permission: serversystem.command.fly  
  group:
    description: Edit permission groups
    usage: /<command> [<group>] [<action>] [<option>] [value]
  inventory:
    description: Open the inventory of a player
    usage: /<command> [<player>]
    permission: serversystem.command.inventory
  lobby:
    description: Teleport player to lobby
    usage: /<command>
    aliases: [hub, h, l]
    permission: serversystem.command.lobby
  permission:
    description: Set the permissions and group of a player
    usage: /<command> [<player>] [<option>] [value]
  permissionreload:
    description: Reloads all permissions for all players
    usage: /<command>
  speed:
    description: Toggle players flyspeed
    usage: /<command> 
    permission: serversystem.command.speed
  vanish:
    description: Allow the player to vanish
    usage: /<command> [<player>]
    permission: serversystem.command.vanish
  warp:
    description: Teleport player to a warp or edit a warp
    usage: /<command> <warp>] [<action>] [<option>] [value]
    permission: serversystem.command.warp
  world:
    description: Teleport player to an other world or edit an other world
    usage: /<command> [<world>] [<action>] [<option>] [value]
    permission: serversystem.command.world
  
permissions:
  serversystem.command.admin:
    description: Open the admin inventory
    default: op
  serversystem.command.back:
    description: Teleport back to the last location
    default: op
  serversystem.command.build:
    description: Allow the player to build in protected worlds
    default: op
  serversystem.command.build.other:
    description: Allow other players to build in protected worlds
    default: op
  serversystem.command.enderchest:
    desciption: Open your enderchest
    default: op
  serversystem.command.enderchest.other:
    desciption: Open an other players enderchest
    default: op
  serversystem.command.fly:
    desciption: Allow the player to fly
    default: op
  serversystem.command.fly.other:
    desciption: Allow other players to fly
    default: op
  serversystem.command.group:
    desciption: Edit permission groups
    default: false
  serversystem.command.inventory:
    desciption: Open the inventory of a player
    default: op
  serversystem.command.lobby:
    description: Teleport player to lobby
    default: true
  serversystem.command.permission:
    description: Set the permissions of a player
    default: false
  serversystem.command.speed:
    description: Toggle players flyspeed
    default: op
  serversystem.command.speed.other:
    description: Toggle other players flyspeed
    default: op
  serversystem.command.vanish:
    description: Vanish the player
    default: op
  serversystem.command.vanish.other:
    description: Vanish other players
    default: op
  serversystem.command.warp:
    description: Teleport player to a warp
    default: true
  serversystem.command.warp.edit:
    description: Edit a warp with the warp command
    default: op
  serversystem.command.world:
    description: Teleport player to an other world
    default: op
  serversystem.command.world.edit:
    description: Edit a world with the world command
    default: op
  serversystem.tools.adminstar:
    description: Open the admin inventory
    default: op
  serversystem.tools.commandblock:
    description: Allow to use commandblocks
    default: false
  serversystem.tools.disabledblocks:
    description: Allow to use in the config disabled blocks
    default: op
  serversystem.tools.signedit:
    description: Allow to create executable signs
    default: op