main: serversystem.main.ServerSystem
name: ServerSystem
version: 1.1
author: Der_Zauberer
api-version: 1.14
 
commands:
  admin:
    desciption: Open the admin inventory
    usage: /<command>
    permission: serversystem.command.admin
  build:
    desciption: Allow the player to build
    usage: /<command> [<player>]
    permission: serversystem.command.build
  vanish:
    desciption: Allow the player to vanish
    usage: /<command> [<player>]
    permission: serversystem.command.vanish
  world:
    desciption: Teleoprt player to an other world
    usage: /<command> [<word>] [<player>]
    permission: serversystem.command.word
  permission:
    desciption: Set the permissions of players
    usage: /<command>
    permission: serversystem.command.permission
  plot:
    desciption: Manage a plot
    usage: /<command> <action> [<player>]
    permission: serversystem.command.plot
    
permissions:
  serversystem.command.admin:
    description: Open the admin inventory
    default: op
  serversystem.command.build:
    description: Allow the player to build
    default: op
  serversystem.command.vanish:
    description: Allow the player to vanish
    default: op
  serversystem.command.world:
    description: Teleoprt player to other world
    default: op
  serversystem.command.permission:
    description: Teleoprt player to other world
    default: false
  serversystem.command.plot:
    description: Manage a plot
    default: true
  serversystem.rank.admin:
    description: Display Admin Prefix
    default: false
  serversystem.rank.moderator:
    description: Display Moderator Prefix
    default: false
  serversystem.rank.developer:
    description: Display Developer Prefix
    default: false
  serversystem.rank.supporter:
    description: Display Supporter Prefix
    default: false
  serversystem.rank.team:
    description: Display Team Prefix
    default: false
  serversystem.rank.operator:
    description: Display Operator Prefix
    default: op
  serversystem.rank.youtuber:
    description: Display YouTuber Prefix
    default: false
  serversystem.rank.premium:
    description: Display Premium Prefix
    default: false
  serversystem.rank.player:
    description: Display Player Prefix
    default: true