main: system.main.System
name: System
version: 1.1
author: Der_Zauberer
api-version: 1.14
 
commands:
  admin:
    desciption: Open the admin inventory
    usage: /<command>
    permission: system.admin
  build:
    desciption: Allow the player to build
    usage: /<command>
    permission: system.build
  vanish:
    desciption: Allow the player to vanish
    usage: /<command>
    permission: system.vanish
    
permissions:
  system.admin:
    description: Open the admin inventory
    default: op
  system.build:
    description: Allow the player to build
    default: op
  system.vanish:
    description: Allow the player to vanish
    default: op